juniper:
  hostname: 192.168.1.221
  groups:
    - routers
  username: root
  password: Test123

sw1:
  hostname: 192.168.1.221
  groups:
    - aruba
  username: admin
  password: admin
  
sw1:
  hostname: 192.168.1.223 
  groups:
    - cisco
  username: admin
  password: admin
  